-- ============================================================================
-- Apparat — demo/seed data. FICTIONAL university, fictional people.
-- All passwords below are the literal string  Demo@123  — hashed with the
-- same PBKDF2WithHmacSHA256 scheme util.PasswordUtil uses at runtime, so the
-- seeded accounts can actually log in. Generated by
-- util.PasswordUtil#main (see that class) — regenerate with:
--   java -cp target/classes com.apparat.util.PasswordUtil Demo@123
-- NEVER use these values, or this password, outside a local/demo database.
-- ============================================================================
USE apparat;

-- Placeholder hash format: PBKDF2$<iterations>$<salt-base64>$<hash-base64>
-- The literal values below are produced at seed-generation time by
-- PasswordUtil and pasted in; see README "Demo credentials" for the caveat.

INSERT INTO users (email, password_hash, full_name, role, department, active) VALUES
('admin@apparat.edu',      'PBKDF2$120000$OxLuvdMPvDypRAIHfiUmWw==$h8GwxYd1Wyhr+u3ZHIp2fWYICsRmgWboRnKjJyATDcc=', 'Ananya Rao',       'ADMIN',      'Central Facilities', 1),
('tech.mehta@apparat.edu', 'PBKDF2$120000$OxLuvdMPvDypRAIHfiUmWw==$h8GwxYd1Wyhr+u3ZHIp2fWYICsRmgWboRnKjJyATDcc=', 'Rohan Mehta',      'TECHNICIAN', 'Materials Science',  1),
('tech.iyer@apparat.edu',  'PBKDF2$120000$OxLuvdMPvDypRAIHfiUmWw==$h8GwxYd1Wyhr+u3ZHIp2fWYICsRmgWboRnKjJyATDcc=', 'Divya Iyer',       'TECHNICIAN', 'Chemistry',          1),
('prof.kapoor@apparat.edu','PBKDF2$120000$OxLuvdMPvDypRAIHfiUmWw==$h8GwxYd1Wyhr+u3ZHIp2fWYICsRmgWboRnKjJyATDcc=', 'Dr. Nikhil Kapoor','FACULTY',    'Physics',            1),
('prof.singh@apparat.edu', 'PBKDF2$120000$OxLuvdMPvDypRAIHfiUmWw==$h8GwxYd1Wyhr+u3ZHIp2fWYICsRmgWboRnKjJyATDcc=', 'Dr. Harleen Singh','FACULTY',    'Chemistry',          1),
('student.arjun@apparat.edu','PBKDF2$120000$OxLuvdMPvDypRAIHfiUmWw==$h8GwxYd1Wyhr+u3ZHIp2fWYICsRmgWboRnKjJyATDcc=','Arjun Verma',     'STUDENT',    'Physics',            1),
('student.meera@apparat.edu','PBKDF2$120000$OxLuvdMPvDypRAIHfiUmWw==$h8GwxYd1Wyhr+u3ZHIp2fWYICsRmgWboRnKjJyATDcc=','Meera Nair',      'STUDENT',    'Materials Science',  1),
('student.kabir@apparat.edu','PBKDF2$120000$OxLuvdMPvDypRAIHfiUmWw==$h8GwxYd1Wyhr+u3ZHIp2fWYICsRmgWboRnKjJyATDcc=','Kabir Malhotra',  'STUDENT',    'Chemistry',          1);

-- Resources — the four instruments named in the build brief
INSERT INTO resources (code, name, resource_type, category, location, description, custodian_id, status,
                        open_time, close_time, slot_minutes, min_slot_minutes, max_slot_minutes,
                        buffer_minutes, requires_certification, requires_approval)
VALUES
('SEM-01',  'Scanning Electron Microscope',        'INSTRUMENT', 'Microscopy',    'Materials Bldg, Rm 204',
 'High-resolution SEM for surface imaging at up to 100,000x magnification.',
 (SELECT id FROM users WHERE email='tech.mehta@apparat.edu'), 'AVAILABLE',
 '09:00:00','18:00:00', 30, 30, 180, 15, 1, 1),

('AFM-01',  'Atomic Force Microscope',              'INSTRUMENT', 'Microscopy',    'Materials Bldg, Rm 206',
 'Contact and tapping-mode AFM for nanoscale surface topography.',
 (SELECT id FROM users WHERE email='tech.mehta@apparat.edu'), 'AVAILABLE',
 '09:00:00','18:00:00', 30, 30, 180, 10, 1, 1),

('HPLC-01', 'High Performance Liquid Chromatograph','INSTRUMENT', 'Analytical Chem','Chemistry Bldg, Rm 112',
 'Reverse-phase HPLC with UV-Vis detector for compound separation and quantification.',
 (SELECT id FROM users WHERE email='tech.iyer@apparat.edu'), 'AVAILABLE',
 '08:00:00','20:00:00', 30, 30, 240, 20, 0, 0),

('XRD-01',  'X-Ray Diffractometer',                 'INSTRUMENT', 'Materials Char.','Materials Bldg, Rm 118',
 'Powder XRD for crystal structure and phase identification.',
 (SELECT id FROM users WHERE email='tech.iyer@apparat.edu'), 'MAINTENANCE',
 '09:00:00','17:00:00', 30, 30, 180, 15, 1, 0);

-- A maintenance window explaining why XRD-01 is MAINTENANCE right now
INSERT INTO maintenance_windows (resource_id, start_at, end_at, reason, created_by)
VALUES ((SELECT id FROM resources WHERE code='XRD-01'),
        DATE_ADD(CURDATE(), INTERVAL 0 DAY), DATE_ADD(CURDATE(), INTERVAL 3 DAY),
        'Annual detector calibration', (SELECT id FROM users WHERE email='tech.iyer@apparat.edu'));

-- A few demo bookings so the dashboard/history/approvals screens aren't empty on first login.
-- Times are anchored to CURDATE() so the seed stays meaningful whenever it's loaded.
INSERT INTO bookings (resource_id, requester_id, start_at, end_at, status, purpose, approved_by, approved_at)
VALUES
((SELECT id FROM resources WHERE code='HPLC-01'),
 (SELECT id FROM users WHERE email='student.kabir@apparat.edu'),
 TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '10:00:00'),
 TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '11:00:00'),
 'APPROVED', 'Column calibration run for thesis samples',
 (SELECT id FROM users WHERE email='tech.iyer@apparat.edu'), NOW()),

((SELECT id FROM resources WHERE code='SEM-01'),
 (SELECT id FROM users WHERE email='student.meera@apparat.edu'),
 TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 2 DAY), '14:00:00'),
 TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 2 DAY), '15:00:00'),
 'PENDING', 'Surface imaging of alloy samples — needs supervisor approval',
 NULL, NULL);

-- Materialize booking_slot rows for the two seeded occupying bookings (mirrors what
-- BookingService.createBooking does at runtime — see service.BookingService).
INSERT INTO booking_slot (booking_id, resource_id, slot_start, is_buffer)
SELECT b.id, b.resource_id, TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '10:00:00'), 0
FROM bookings b JOIN resources r ON r.id=b.resource_id WHERE r.code='HPLC-01' AND b.status='APPROVED';
INSERT INTO booking_slot (booking_id, resource_id, slot_start, is_buffer)
SELECT b.id, b.resource_id, TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '10:30:00'), 0
FROM bookings b JOIN resources r ON r.id=b.resource_id WHERE r.code='HPLC-01' AND b.status='APPROVED';

INSERT INTO booking_slot (booking_id, resource_id, slot_start, is_buffer)
SELECT b.id, b.resource_id, TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 2 DAY), '14:00:00'), 0
FROM bookings b JOIN resources r ON r.id=b.resource_id WHERE r.code='SEM-01' AND b.status='PENDING';
INSERT INTO booking_slot (booking_id, resource_id, slot_start, is_buffer)
SELECT b.id, b.resource_id, TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 2 DAY), '14:30:00'), 0
FROM bookings b JOIN resources r ON r.id=b.resource_id WHERE r.code='SEM-01' AND b.status='PENDING';

-- Quota rows for the current ISO week (STUDENT default: 120 min/week)
INSERT INTO quota_usage (user_id, iso_year, iso_week, used_minutes, limit_minutes)
SELECT id, YEAR(CURDATE()), WEEK(CURDATE(), 3), 0, 120 FROM users WHERE role='STUDENT';
